# Generated by Django 3.1.2 on 2021-07-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
                ('fips', models.IntegerField(default=0, verbose_name='fips')),
                ('hospBedNeeded', models.BigIntegerField(null=True, verbose_name='Hospital Beds Needed')),
                ('criticCareNeeded', models.BigIntegerField(null=True, verbose_name='Critical Care Needed')),
                ('ventNeeded', models.BigIntegerField(null=True, verbose_name='Ventilator Needed')),
                ('tothospBedNeeded', models.BigIntegerField(null=True, verbose_name='Total Hospital Beds Needed on Date')),
                ('totCriticCareNeeded', models.BigIntegerField(null=True, verbose_name='Total Critical Care Needed on Date')),
                ('totVentNeeded', models.BigIntegerField(null=True, verbose_name='Total Ventilator Needed on Date')),
            ],
            options={
                'db_table': 'state_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsStatesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
                ('fips', models.IntegerField(default=0, verbose_name='Fips')),
                ('cases', models.BigIntegerField(null=True, verbose_name='Total Cases')),
                ('deaths', models.BigIntegerField(null=True, verbose_name='Total Deaths')),
                ('newCases', models.BigIntegerField(null=True, verbose_name='New Cases')),
                ('newDeaths', models.BigIntegerField(null=True, verbose_name='New Deaths')),
            ],
            options={
                'db_table': 'us_states_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('day', models.BigIntegerField(null=True, verbose_name='Day')),
                ('month', models.BigIntegerField(null=True, verbose_name='Month')),
                ('year', models.BigIntegerField(null=True, verbose_name='Year')),
                ('newCases', models.BigIntegerField(null=True, verbose_name='New Cases')),
                ('newDeaths', models.BigIntegerField(null=True, verbose_name='New Deaths')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('geoID', models.CharField(max_length=200, verbose_name='Geo Location ID')),
            ],
            options={
                'db_table': 'world_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorldReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('geoID', models.CharField(max_length=200, verbose_name='Geo Location ID')),
                ('hospBedNeeded', models.BigIntegerField(null=True, verbose_name='Hospital Beds Needed')),
                ('criticCareNeeded', models.BigIntegerField(null=True, verbose_name='Critical Care Needed')),
                ('ventNeeded', models.BigIntegerField(null=True, verbose_name='Ventilator Needed')),
                ('tothospBedNeeded', models.BigIntegerField(null=True, verbose_name='Total Hospital Beds Needed on Date')),
                ('totCriticCareNeeded', models.BigIntegerField(null=True, verbose_name='Total Critical Care Needed on Date')),
                ('totVentNeeded', models.BigIntegerField(null=True, verbose_name='Total Ventilator Needed on Date')),
            ],
            options={
                'db_table': 'world_report',
                'managed': True,
            },
        ),
    ]
